import org.jetbrains.gradle.ext.Gradle

plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.1.7'
    id 'eclipse'
    id 'com.gtnewhorizons.retrofuturagradle' version '1.3.33'
    id 'com.matthewprenger.cursegradle' version '1.4.0'
}

version = project.mod_version
group = project.maven_group
archivesBaseName = project.archives_base_name

// Set the toolchain version to decouple the Java we run Gradle with from the Java used to compile and run the mod
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
        // Azul covers the most platforms for Java 8 toolchains, crucially including MacOS arm64
        vendor.set(org.gradle.jvm.toolchain.JvmVendorSpec.AZUL)
    }
    // Generate sources and javadocs jars when building and publishing
    withSourcesJar()
    // withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

configurations {
    embed
    implementation.extendsFrom(embed)
}

minecraft {
    mcVersion = '1.12.2'

    // MCP Mappings
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'

    // Set username here, the UUID will be looked up automatically
    username = 'Developer'

    // Add any additional tweaker classes here
    //extraTweakClasses.add('org.spongepowered.asm.launch.MixinTweaker')

    // Add various JVM arguments here for runtime
    def args = ["-ea:${project.group}"]
    if (project.use_coremod.toBoolean()) {
        args << '-Dfml.coreMods.load=' + coremod_plugin_class_name
    }
    if (project.use_mixins.toBoolean()) {
        args << '-Dmixin.hotSwap=true'
        args << '-Dmixin.checks.interfaces=true'
        args << '-Dmixin.debug.export=true'
    }
    extraRunJvmArguments.addAll(args)

    // Include and use dependencies' Access Transformer files
    useDependencyAccessTransformers = true

    // Add any properties you want to swap out for a dynamic value at build time here
    // Any properties here will be added to a class at build time, the name can be configured below
    injectedTags.put('MOD_ID', project.mod_id)
    injectedTags.put('MOD_NAME', project.mod_name)
    injectedTags.put('VERSION', project.version)
}

// Generate a group.mod_id.Tags class
tasks.injectTags.configure {
    // Change Tags class' name here:
    outputClassName.set("${project.group}.${project.mod_id}.Tags")
}

repositories {
    maven {
        name 'CleanroomMC Maven'
        url 'https://maven.cleanroommc.com'
    }
    maven {
        name 'SpongePowered Maven'
        url 'https://repo.spongepowered.org/maven'
    }
    maven {
        name 'CurseMaven'
        url 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'Mod Maven'
        url = 'https://modmaven.dev'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    mavenLocal() // Must be last for caching to work
}

dependencies {
    // Libraries
    if (project.use_assetmover.toBoolean()) {
        implementation 'com.cleanroommc:assetmover:2.5'
    }
    if (project.use_mixins.toBoolean()) {
        implementation 'zone.rong:mixinbooter:9.1'
    }
    implementation 'com.cleanroommc:configanytime:2.0'

    implementation 'com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2'
    embed 'com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2'
    implementation 'com.udojava:EvalEx:2.7'
    embed 'com.udojava:EvalEx:2.7'

    implementation "CraftTweaker2:CraftTweaker2-API:" + project.version_crafttweaker
    implementation "CraftTweaker2:ZenScript:" + project.version_crafttweaker
    implementation "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-" + project.version_crafttweaker

    // Mods
    implementation rfg.deobf("curse.maven:ctm-224791:2822288")
    implementation rfg.deobf("curse.maven:arcane-archives-311357:3057332")
    implementation rfg.deobf("curse.maven:another-liquid-milk-319900:2703510")
    implementation rfg.deobf("curse.maven:mystical-gears-317915:3206298")
    implementation rfg.deobf("curse.maven:darknesslib-349174:3672570")
    implementation("curse.maven:pizzacraft-292056:2986635")
    implementation rfg.deobf("curse.maven:mysticallib-277064:3483816")
    implementation rfg.deobf("curse.maven:roots-246183:5193525")
    implementation rfg.deobf("curse.maven:eyes-in-the-darkness-304719:2812571")
    implementation rfg.deobf("curse.maven:growthcraft-community-edition-235092:5172498")
    implementation rfg.deobf("curse.maven:sanity-304817:2630361")
    implementation rfg.deobf("curse.maven:soot-extended-life-982730:5156451")
    implementation rfg.deobf("curse.maven:embers-extended-life-936489:5264855")
    implementation rfg.deobf("curse.maven:thaumcraft-223628:2629023")
    implementation rfg.deobf("curse.maven:thaumic-periphery-293505:2766866")
    implementation rfg.deobf("curse.maven:angry-pixel-the-betweenlands-mod-243363:4479688")
    implementation rfg.deobf("curse.maven:thaumic-augmentation-319441:5129455")
    implementation rfg.deobf("curse.maven:botania-225643:3330934")
    implementation rfg.deobf("curse.maven:quark-243121:2924091")
    implementation rfg.deobf("curse.maven:betweenlands-redstone-567792:5237598")
    implementation rfg.deobf("curse.maven:arcane-world-fixed-865605:4551027")
    implementation rfg.deobf("curse.maven:basketcase-304338:3793346")
    implementation rfg.deobf("curse.maven:blockcraftery-278882:2716712")
    implementation rfg.deobf("curse.maven:charset-immersion-291374:2745007")
    implementation rfg.deobf("curse.maven:corpse-316582:3010808")
    implementation rfg.deobf("curse.maven:fairy-lights-233342:3068499")
    implementation rfg.deobf("curse.maven:fire-spread-tweaks-446366:3220632")
    implementation rfg.deobf("curse.maven:fishs-undead-rising-321139:5107583")
    implementation rfg.deobf("curse.maven:ftb-quests-forge-289412:3156637")
    implementation rfg.deobf("curse.maven:grue-235133:3425511")
    implementation rfg.deobf("curse.maven:item-stages-280316:2810185")
    implementation rfg.deobf("curse.maven:livingchest-580230:3754820")
    implementation rfg.deobf("curse.maven:pyrotech-306676:5210730")
    implementation rfg.deobf("curse.maven:realistic-storage-389733:2994129")
    implementation rfg.deobf("curse.maven:recurrent-complex-223150:4643434")
    implementation rfg.deobf("curse.maven:redstone-paste-67508:2477676")
    implementation rfg.deobf("curse.maven:simpledifficulty-360779:3548175")
    implementation rfg.deobf("curse.maven:starterkits-298921:2691539")
    implementation rfg.deobf("curse.maven:storage-drawers-223852:4655859")
    implementation rfg.deobf("curse.maven:tea-the-story-293030:2933372")
    implementation rfg.deobf("curse.maven:thaumic-jei-285492:2705304")
    implementation rfg.deobf("curse.maven:tool-belt-260262:3459767")
    implementation rfg.deobf("curse.maven:athenaeum-284350:4633750")
    implementation rfg.deobf("curse.maven:delivery-306540:2774818")
    implementation rfg.deobf("curse.maven:delivery-merchants-339350:2854820")
    implementation rfg.deobf("curse.maven:baubles-227083:2518667")
    implementation rfg.deobf("curse.maven:antique-atlas-227795:2823030")
    implementation rfg.deobf("curse.maven:game-stages-268655:2951840")
    implementation rfg.deobf("curse.maven:hwyla-253449:2568751")
    implementation rfg.deobf("curse.maven:time-is-up-437596:3900381")
    implementation rfg.deobf("curse.maven:autoreglib-250363:2746011")
    implementation rfg.deobf("curse.maven:lemonlib-306926:2639879")
    implementation rfg.deobf("curse.maven:primal-lib-409199:3779388")
    implementation rfg.deobf("curse.maven:jei-238222:5101347")
    implementation rfg.deobf("curse.maven:patchouli-306770:3162874")
    implementation rfg.deobf("curse.maven:ftblib-237167:2985811")
    implementation rfg.deobf("curse.maven:bookshelf-228525:2836960")
    implementation rfg.deobf("curse.maven:mysticalmechanics-300742:3006392")
    implementation rfg.deobf("curse.maven:guidebook-253874:2989594")
    implementation rfg.deobf("curse.maven:mystical-world-282940:3460961")
    implementation rfg.deobf("curse.maven:item-filters-309674:3003364")
    implementation rfg.deobf("curse.maven:aetherworks-extended-life-1003576:5263747")
    implementation rfg.deobf("curse.maven:immersive-engineering-231951:2974106")
    implementation rfg.deobf("curse.maven:aether-ii-223796:2960610")
    implementation rfg.deobf("curse.maven:topography-297878:3994737")
    implementation rfg.deobf("curse.maven:bnbgaminglib-229587:2698688")
    implementation rfg.deobf("curse.maven:heterorustichromia-363734:2980748")
    implementation rfg.deobf("curse.maven:misctweaks_-245603:2709481")
    implementation rfg.deobf("curse.maven:rustic-256141:6031613")

    runtimeOnly("curse.maven:guide-api-228832:2645992")
    runtimeOnly("curse.maven:collective-342584:3533131")
    runtimeOnly("curse.maven:geckolib-388172:4020277")
    runtimeOnly("curse.maven:ivtoolkit-224535:2443253")
    runtimeOnly("curse.maven:tiffitlib-295414:2631741")
    runtimeOnly("curse.maven:valkyrielib-245480:2691542")
    runtimeOnly("curse.maven:chameleon-230497:2450900")
    runtimeOnly("curse.maven:dropt-284973:3758733")

    implementation files('libs/IgniteHUD-b0.5.4-deobf.jar')
    implementation files('libs/TheBetweenlands-3.9.6-core-deobf.jar')
    implementation files('libs/orbis-lib-1.12.2-0.2.0+build411.jar')

    if (project.use_mixins.toBoolean()) {
        String mixin = modUtils.enableMixins("zone.rong:mixinbooter:9.1", "refmap.bladditions.json")
        api(mixin) {
            transitive = false
        }
        annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
        annotationProcessor 'com.google.guava:guava:24.1.1-jre'
        annotationProcessor 'com.google.code.gson:gson:2.8.6'
        annotationProcessor(mixin) {
            transitive = false
        }
    }
}

// Adds Access Transformer files to tasks
if (project.use_access_transformer.toBoolean()) {
    for (File at : sourceSets.getByName("main").resources.files) {
        if (at.name.toLowerCase().endsWith("_at.cfg")) {
            tasks.deobfuscateMergedJarToSrg.accessTransformerFiles.from(at)
            tasks.srgifyBinpatchedJar.accessTransformerFiles.from(at)
        }
    }
}

processResources {
    // This will ensure that this task is redone when the versions change
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    // Replace various properties in mcmod.info and pack.mcmeta if applicable
    filesMatching(['mcmod.info', 'pack.mcmeta']) { fcd ->
        // Replace version and mcversion
        fcd.expand('version': project.version,
                'mcversion': project.minecraft.version)
    }

    if (project.use_access_transformer.toBoolean()) {
        rename '(.+_at.cfg)', 'META-INF/$1' // Make sure Access Transformer files are in META-INF folder
    }
}

jar {
    manifest {
        def attribute_map = [:]
        if (project.use_coremod.toBoolean()) {
            attribute_map['FMLCorePlugin'] = project.coremod_plugin_class_name
            if (project.include_mod.toBoolean()) {
                attribute_map['FMLCorePluginContainsFMLMod'] = true
                attribute_map['ForceLoadAsMod'] = project.gradle.startParameter.taskNames[0] == "build"
            }
        }
        if (project.use_access_transformer.toBoolean()) {
            attribute_map['FMLAT'] = project.mod_id + '_at.cfg'
        }
        attributes(attribute_map)
    }
    // Add all embedded dependencies into the jar
    from(provider { configurations.embed.collect { it.isDirectory() ? it : zipTree(it) } })
}

idea {
    module {
        inheritOutputDirs = true
    }
    project {
        settings {
            runConfigurations {
                "1. Run Client"(Gradle) {
                    taskNames = ["runClient"]
                }
                "2. Run Server"(Gradle) {
                    taskNames = ["runServer"]
                }
                "3. Run Obfuscated Client"(Gradle) {
                    taskNames = ["runObfClient"]
                }
                "4. Run Obfuscated Server"(Gradle) {
                    taskNames = ["runObfServer"]
                }
            }
            compiler.javac {
                afterEvaluate {
                    javacAdditionalOptions = "-encoding utf8"
                    moduleJavacAdditionalOptions = [(project.name + ".main"): tasks.compileJava.options.compilerArgs.collect { '"' + it + '"' }.join(' ')]
                }
            }
        }
    }
}

tasks.named("processIdeaSettings").configure {
    dependsOn("injectTags")
}
